#' @title Pairwise extraction of omega correlations
#' @description Pairwise extraction of omega correlations read.lst object to data frame
#' @param listobject list object generated by read.lst
#' @param omegas character vector with omega parameters with correlation
#' @param correlations 
#' @param occ correlation from BOV parameters?, Default=F 
#' @param signif number of significant digits for estimates etc, Default: 3
#' @return summarized data frame
#' @rdname lst_cor_extract
#' @export 
#' @importFrom dplyr bind_rows

lst_cor_extract <- function(listobject, omegas, 
                            correlations, signif=3, occ=F) {
  
  # idiocy, should be replaced
  
  if(occ==F){
    par1 <- paste0("BSV_", correlations[1])
    par2 <- paste0("BSV_", correlations[2])
  } else {
    par1 <- paste0("IOV_", correlations[1])
    par2 <- paste0("IOV_", correlations[2])
  }
  
  position1 <- which(omegas %in% par1)
  position2 <- which(omegas %in% par2)
  
  pos1 <- min(position1, position2)
  pos2 <- max(position1, position2)
  
  var1 <- listobject$omega[[pos1]][[pos1]]
  var2 <- listobject$omega[[pos2]][[pos2]]

  covariance   <- listobject$omega[[pos2]][pos1]
  secovariance <- listobject$seomega[[pos2]][pos1]
  rse <- (secovariance/covariance)*100
    
  correlation  <- covariance / (sqrt(var1) * sqrt(var2))

  return(data.frame(par = paste("Cor",correlations[1],correlations[2], sep="_"),
                    estimate = signif(correlation, digits=signif),
                    CV = NA,
                    SD = NA,
                    SE = signif(secovariance, digits=signif),
                    RSE = signif(abs(rse), digits=signif),
                    Shrink = NA))
}

