#' @title Extract model parameters from read.lst object to data frame
#' @description Extract model parameters from read.lst object to data frame
#' @param listobject list object generated by read.lst
#' @param theta_parms character vector with theta parameters
#' @param omega_parms character vector with omega parameters
#' @param sigma_parms character vector with sigma parameters
#' @param signif number of significant digits for estimates etc, Default: 3
#' @return summarized data frame
#' @seealso 
#'  \code{\link[dplyr]{bind_rows}}
#' @rdname lst_par_extract
#' @export 
#' @importFrom dplyr bind_rows

lst_par_extract <- function(listobject, 
                            theta_parms,
                            omega_parms, 
                            sigma_parms, 
                            signif=3) {
  
  # idiocy, should be replaced
  
  n_theta_pars <- length(theta_parms)
  n_omega_pars <- length(omega_parms)
  n_sigma_pars <- length(sigma_parms)
  
  # thetas
  tPars <- data.frame(par=theta_parms, stringsAsFactors=F)
  tPars$estimate <- listobject$thetas
  tPars$SE <- listobject$sethetas
  tPars$RSE <- (listobject$sethetas /tPars$estimate)*100

  # omegas
  oPars <- data.frame(par=omega_parms, stringsAsFactors=F)
  
  for(i in 1:n_omega_pars){
    diag <- listobject$omega[[i]][[i]]
    if(i==1){
      estimate <- diag
    }else{
      estimate <- c(estimate, diag)
    }
  }
  oPars$estimate <- estimate
  oPars$CV <- sqrt(oPars$estimate)*100
  for(i in 1:n_omega_pars){
    diag <- listobject$seomega[[i]][[i]]
    if(i==1){
      estimate <- diag
    }else{
      estimate <- c(estimate, diag)
    }
  }
  oPars$SE <- estimate
  oPars$RSE <- (oPars$SE/oPars$estimate)*100
  
  # shrinkage
  if(n_omega_pars <= 10){
    oPars$Shrink <- as.numeric(
      str_split(listobject$term[str_detect(listobject$term, "ETAshrink")], "  ")[[1]][-1])
    # oPars$ebvShrink <- as.numeric(
    #   str_split(listobject$term[str_detect(listobject$term, "EBVshrink")], "  ")[[1]][-1])
  } else {
    oPars$Shrink <- rep(NA, n_omega_pars)
    oPars$Shrink[1:10] <- as.numeric(
      str_split(listobject$term[str_detect(listobject$term, "ETAshrink")], "  ")[[1]][-1])
    pos <- which(str_detect(listobject$term, "ETAshrink") == "TRUE") + 1
    oPars$Shrink[11:n_omega_pars] <- as.numeric(
      str_split(listobject$term[pos], "  ")[[1]][str_split(listobject$term[pos], "  ")[[1]] != ""])
    }
  
  # sigmas
  sPars <- data.frame(par = sigma_parms, stringsAsFactors=F)
  for(i in 1:n_sigma_pars){
    diag <- listobject$sigma[[i]][[i]]
    if(i==1){
      estimate <- diag
    }else{
      estimate <- c(estimate, diag)
    }
  }
  sPars$estimate <- estimate
  sPars$SD <- sqrt(sPars$estimate)
  for(i in 1:n_sigma_pars){
    diag <- listobject$sesigma[[i]][[i]]
    if(i==1){
      estimate <- diag
    }else{
      estimate <- c(estimate, diag)
    }
  }
  sPars$SE <- estimate
  sPars$RSE <- (sPars$SE / sPars$estimate)*100
  
  # shrinkage
  sPars$Shrink <- as.numeric(
    str_split(listobject$term[str_detect(listobject$term, "EPSshrink")], "  ")[[1]][-1])
  
  
  # Bind all parameters together
  Pars <- dplyr::bind_rows(tPars, oPars, sPars)

  ## Round and format
  Pars$RSE  <- abs(Pars$RSE)
  Pars[,c("estimate", "SE", "RSE", "CV", "Shrink", "SD")] <- 
    signif(Pars[,c("estimate", "SE", "RSE", "CV", "Shrink", "SD")], 
           digits=signif)

  return(Pars[,c("par", "estimate", "CV", "SD", "SE", "RSE", "Shrink")])
}
